### ISSUE TITLE
Option to have the checkbox enabled by default

### ISSUE THREAD

**Issue by ricardocostaza** [cyrillbolliger/conditional-featured-image#15]
An option to have the checkbox enabled by default  when creating a new post would be useful.
Is there a workaround to get it? Thanks.

**Comment by cyrillbolliger** [comment]
Thanks for the suggestion. I've just added a [filter](https://developer.wordpress.org/reference/functions/add_filter/) for this and released an update. So since version 2.4.0 it **is now possible to enable the checkbox by default**.

To preselect the checkbox, you may **just add the following line to your `functions.php`**:
```php
add_filter( 'cybocfi_hide_by_default', '__return_true' );
```

You may also have different setting for every post type:
```PHP
function cybocfi_set_default_hiding_state( $default, $post_type ) {
    if ( 'post' === $post_type ) {
        $default = true; // set the default state for posts
    } else if ( 'page' === $post_type ) {
        $default = false; // set the default state for pages
    }

    return $default;
}
add_filter( 'cybocfi_hide_by_default', 'cybocfi_set_default_hiding_state', 10, 2 );
```
